services:
  web:
    image: 'gitlab/gitlab-ce:17.7.0-ce.0'
    restart: always
    hostname: '192.168.242.46'
    container_name: gitlab-ce
    user: root
    environment:
      GITLAB_SIGNUP_ENABLED: false
      GITLAB_ROOT_EMAIL: "admin@buildwithlal.com"
      GITLAB_ROOT_PASSWORD: "D2eo3BzW#EeXveRe"
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost'
        gitlab_rails['registry_enabled'] = true
        gitlab_rails['gitlab_shell_ssh_port'] = 2424
        registry_external_url 'http://localhost:5005'
    ports:
      - '80:80'
      - '443:443'
      - '2424:22'
      - '5005:5005'
    volumes:
      - '/home/chai/sannonthachai/gitlab/config:/etc/gitlab'
      - '/home/chai/sannonthachai/gitlab/logs:/var/log/gitlab'
      - '/home/chai/sannonthachai/gitlab/data:/var/opt/gitlab'
    networks:
      - gitlab
  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    container_name: gitlab-runner
    restart: always
    user: root
    depends_on:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - '/home/chai/sannonthachai/gitlab/gitlab-runner:/etc/gitlab-runner'
    networks:
      - gitlab

networks:
  gitlab:
    name: gitlab-network

