services:
  web:
    image: 'gitlab/gitlab-ce:18.3.2-ce.0'
    restart: always
    hostname: gitlab
    container_name: gitlab-ce
    user: root
    environment:
      GITLAB_SIGNUP_ENABLED: false
      GITLAB_ROOT_EMAIL: ""
      GITLAB_ROOT_PASSWORD: ""
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://10.23.11.10'
        gitlab_rails['gitlab_signup_enabled'] = false
        gitlab_rails['registry_enabled'] = true
        gitlab_rails['gitlab_shell_ssh_port'] = 2424
        gitlab_rails['time_zone'] = 'Asia/Bangkok'
        registry_external_url 'http://10.23.11.10:5005'
    ports:
      - '80:80'
      - '443:443'
      - '2424:22'
      - '5005:5005'
    volumes:
      - '/home/sannonthachai.tun/gitlab/config:/etc/gitlab'
      - '/home/sannonthachai.tun/gitlab/logs:/var/log/gitlab'
      - '/home/sannonthachai.tun/gitlab/data:/var/opt/gitlab'
    networks:
      - gitlab
  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    container_name: gitlab-runner
    restart: always
    user: root
    depends_on:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - '/home/sannonthachai.tun/gitlab/gitlab-runner:/etc/gitlab-runner'
    networks:
      - gitlab

networks:
  gitlab:
    name: gitlab-network

