concurrent = 1
check_interval = 0
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "cd /et\tgitl"
  url = "http://dv-srv-gl.divineconnect.co.th"
  id = 2
  token = "token"
  token_obtained_at = 2025-09-17T09:28:41Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  environment = ["DOCKER_AUTH_CONFIG={\"auths\":{\"dv-srv-gl.dwl.local:5005\":{\"auth\":\"docker_config_json_base64\"}}}"]
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "docker:stable"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    shm_size = 0
    network_mtu = 0
    volumes = ["/var/run/docker.sock:/var/run/docker.sock","/cache"]
    pull_policy = "if-not-present"
